require('./specs/composr.test.js');
require('./specs/init.test.js');
require('./specs/bindConfiguration.test.js');
require('./specs/logClient.test.js');
require('./specs/fetchData.test.js');
require('./specs/registerData.test.js');
require('./specs/utils.test.js');
require('./specs/events.test.js');
require('./specs/validators/validate.utils.test.js');
//require('./specs/Phrases.test.js');
require('./specs/Publisher.test.js');
require('./specs/regexpGenerator.test.js');
require('./specs/paramsExtractor.test.js');

/*require('./specs/snippetsBundler.js');
require('./specs/composerError.js');
require('./specs/phraseManager.js');
require('./specs/docBuilder.js');
require('./specs/phraseValidator.js');
*/