require('./specs/composr.test.js');
require('./specs/logClient.test.js');
require('./specs/regexpGenerator.js');
require('./specs/paramsExtractor.js');
/*require('./specs/snippetsBundler.js');
require('./specs/composerError.js');
require('./specs/phraseManager.js');
require('./specs/docBuilder.js');
require('./specs/phraseValidator.js');
*/