sudo: false
language: node_js
node_js:
  - "5.10.1"

notifications:
  email:
    - "rafael.pedrola@bq.com"
    - "jorge.serrano@bq.com"
    - "josep.arpi@bq.com"
    - "miguel.jimenez@bq.com"

addons:
  code_climate:
    repo_token: 4db1d31b1d02b573dc56844161c97c9038d388574c5d4168e36f6d330121782a

before_install:
  - npm install -g grunt-cli
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter

after_script:
  - istanbul cover node_modules/.bin/_mocha -- -R dot
  - codeclimate-test-reporter < coverage/lcov.info